In [21]:
import pandas as pd
import numpy as np

In [90]:
# reading a csv file as dataframe
df1 = pd.read_csv('milldata.csv')

In [ ]:
# creating function to create df1
# get familiar with the data first, open it using excel

In [91]:
# listing the column headers
display(list(df1.columns.values))

['SL#',
 'MILLER_CODE',
 'MILLING_CAP',
 'CAPACITY_2',
 'PERFORMANCE_STATUS',
 'PADDY_LIFTED',
 'ADDITIONAL_SECURITY',
 'RICE_DELIVERED_QTL']

In [92]:
# creating a new dataframe with 2nd, 3rd, and 5th columns of df1
df2 = df1.iloc[:, [1, 2, 4]]

In [93]:
# sort the new dataframe by its 2nd column
df2.sort_values("MILLING_CAP")

MILLER_CODE  MILLING_CAP PERFORMANCE_STATUS
7     M010601       120000                 no
4     M010302       131500                yes
3     M010301       136000                yes
5     M010303       143300                 no
1     M010102       154550                yes
6     M010402       154550                yes
2     M010201       160000                 no
0     M010101       163000                yes

In [87]:
# creating a function which outputs df2

def dataframefilter(fl):
    df1=pd.read_csv(fl)
    hdr1 = list(df1)
    df2=df1[[hdr1[1], hdr1[2], hdr1[4]]]
    hdr2 = list(df2)
    df2s = df2.sort_values(hdr2[1])
    return(df2s)

In [88]:
dataframefilter('milldata.csv')

MILLER_CODE  MILLING_CAP PERFORMANCE_STATUS
7     M010601       120000                 no
4     M010302       131500                yes
3     M010301       136000                yes
5     M010303       143300                 no
1     M010102       154550                yes
6     M010402       154550                yes
2     M010201       160000                 no
0     M010101       163000                yes

In [102]:
## Adding a filter into the dataframe
# extract the data with milling cap > 150000 and performance status is yes

hdr2= list(df2)
hdr2

df3 = df2.loc[(df2[hdr2[1]] > 150000) & (df2[hdr2[2]] == "yes")]
df3

MILLER_CODE  MILLING_CAP PERFORMANCE_STATUS
0     M010101       163000                yes
1     M010102       154550                yes
6     M010402       154550                yes

In [14]:
#------------------------------------------------------------------
# Create a 3x4 matrix A contains 0

a = (3, 4)
A = np.zeros(a, dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
# put 1 in matrix A if the sum of indices is odd

for a in range(A.shape[0]):
    for i in range(A.shape[1]):
        if ((a+i)%2) == 1:
            A[a,i] = 1
A 

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [62]:
# Create a vector X of dimension 12, consisting of all 1<= x <=12

X = np.arange(1,13)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
# Reshape X into a 3x4 matrix B

B = np.reshape(X, (3, 4))
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
# add matrix A and B

A+B

array([[ 1,  3,  3,  5],
       [ 6,  6,  8,  8],
       [ 9, 11, 11, 13]])

In [27]:
#--------------------------------------------------------------------------------------
# create a numpy array C for the coefficient matrix in the equation

C = np.array([[3, 2], [2, -1]])
C

array([[ 3,  2],
       [ 2, -1]])